# Copilot, please generate a GitHub Action workflow to: Build a Docker image from a Dockerfile, Tag the image with the GitHub commit SHA, Login to GitHub Container Registry (GHCR), Push the image to GHCR
on:
  push:
   branches:
   - den-vasyliev-patch-2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --tag image-name:${GITHUB_SHA}
    - name: Log into GHCR
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push to GHCR
      run: docker push ghcr.io/owner/image-name:${GITHUB_SHA}







