# Please generate a GitHub Actions workflow file (YAML) that performs the following tasks:

# 1. Trigger the workflow on every push to the main branch.
# 2. Checkout the repository.
# 3. Build a Docker container using the Dockerfile located in the repository's root directory.
# 4. Log in to GitHub Container Registry (GHCR) using a GitHub Personal Access Token (PAT) with the appropriate permissions.
# 5. Tag the Docker container with the repository's name and the commit SHA as the version.
# 6. Push the Docker container to GHCR under the repository's owner account.

# The workflow should be named "Docker" and should be placed in the .github/workflows directory.

# The workflow should be triggered on every push to the main branch.
on:
  push:
    branches:
      - den-vasyliev-patch-5

# The workflow should be named "Docker" and should be placed in the .github/workflows directory.
name: Docker

# The workflow should perform the following tasks:
jobs:
  build:
    # 1. Trigger the workflow on every push to the main branch.
    # 2. Checkout the repository.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 3. Build a Docker container using the Dockerfile located in the repository's root directory.
      - name: Build
        run: docker build -t docker .
      # 4. Log in to GitHub Container Registry (GHCR) using a GitHub Personal Access Token (PAT) with the appropriate permissions.
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # 5. Tag the Docker container with the repository's name and the commit SHA as the version.
      - name: Tag
        run: docker tag docker ghcr.io/${{ github.repository_owner }}/docker:${{ github.sha }}
      # 6. Push the Docker container to GHCR under the repository's owner account.
      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/docker:${{ github.sha }}

