# # Generate a GitHub Actions workflow YAML file that builds a Docker container from a Dockerfile in the root directory of the repository and pushes it to GitHub Container Registry (GHCR). The workflow should trigger on every push to the main branch and should use the latest version of Ubuntu as the runner. It should authenticate with GHCR and should tag the container with the current date and time in UTC format.

name: Build and push Docker container to GHCR

on:
  push:
    branches:
      - den-vasyliev-patch-4

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Log into GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}


  
